class bag{
    constructor(size){
        this.size=size;
        this.init();
    }
    putin(otherBag){
        this.item.forEach((item,index)=>{
            item.amount+=otherBag.item[index].amount;
            otherBag.item[index].amount=0;
        });
    }
    init(){
        this.item=[
            {
                "name":"饮用水",
                "img":"",
                "amount":1
            }
        ]
    }
}