class Event{
    constructor(){
        this.end=false;
        this.canEnd=false;
        this.recipe1=false;
        this.recipe2=false;
        this.recipe3=false;
        this.recipe4=false;
    }
}
class eventChecker{
    constructor(){
        this.event=new Event;
    }
    update(game){
        if(!this.event.recipe1&&game.bag.item[1].amount>0){
            this.event.recipe1=true;
            game.bag.subItem("冶炼秘术",1);
            game.RecipeGroup.recipe.push(
                {
                    "name":"丝薇丽银",
                    "time":8,
                    "recipe":{
                        "石灰岩":1,
                        "中和剂（红）":1,
                        "（石材）":2
                    }
                },
                {
                    "name":"十字镐",
                    "time":16,
                    "recipe":{
                        "丝薇丽银":2,
                        "金属块":1,
                        "直木":2
                    }
                },
            );
        }
        if(!this.event.recipe2&&game.bag.item[2].amount>0){
            this.event.recipe2=true;
            game.bag.subItem("高等冶炼术",1);
            game.RecipeGroup.recipe.push(
                {
                    "name":"黄金艾森矿",
                    "time":16,
                    "recipe":{
                        "黄金色之岩":1,
                        "雷电矿":2,
                        "中和剂（黄）":2
                    }
                },
                {
                    "name":"精灵银块",
                    "time":32,
                    "recipe":{
                        "残破矿石":2,
                        "七色棱镜":1,
                        "（龙素材）":1
                    }
                }
            );
        }
        if(!this.event.recipe3&&game.bag.item[3].amount>0){
            this.event.recipe3=true;
            game.bag.subItem("宝石雕刻术",1);
            game.RecipeGroup.recipe.push(
                {
                    "name":"纯洁钻石",
                    "time":12,
                    "recipe":{
                        "睿智绿宝石":1,
                        "钻石原石":2,
                        "（水）":4
                    }
                },
                {
                    "name":"百万水晶",
                    "time":10,
                    "recipe":{
                        "纯洁钻石":1,
                        "纯水":2,
                        "（神秘之力）":3
                    }
                },
                {
                    "name":"七色棱镜",
                    "time":10,
                    "recipe":{
                        "万能中和剂（虹）":1,
                        "纯水":4,
                        "（原石）":2
                    }
                },
            );
        }
        if(!this.event.recipe4&&game.bag.item[7].amount>0){
            this.event.recipe4=true;
            game.bag.subItem("炸弹的制作方法",1);
            game.RecipeGroup.recipe.push(
                {
                    "name":"爆破用炎烧",
                    "time":4,
                    "recipe":{
                        "中和剂（红）":2,
                        "（火药）":1,
                        "（燃料）":2
                    }
                }
            );
        }
        if(game.timer>=2880){
            this.event.end=true;
        }
        if(game.storage.item[0].amount>=1){
            this.event.canEnd=true;
        }
        if(this.event.end){
            game.changeMap(atelier);
            localStorage.removeItem("LA-save-"+localStorage.getItem("LA-username"));
            if(game.storage.item[0].amount==0){
                game.achievement.getAchievement("坏结局",game);
                window.location.href="../html/end.html?ending=bad";
            }
            else if(Math.max(...game.storage.item[0].quality)<=500){
                game.achievement.getAchievement("普通结局",game);
                window.location.href="../html/end.html?ending=normal";
            }
            else if(Math.max(...game.storage.item[0].quality)>500&&game.storage.item[game.storage.itemID("贤者之石")].amount==0){
                game.achievement.getAchievement("好结局",game);
                window.location.href="../html/end.html?ending=good";
            }
            else{
                game.achievement.getAchievement("真结局",game);
                window.location.href="../html/end.html?ending=best";
            }
        }
        if(game.status=="paused"&&this.event.canEnd){
            document.getElementById("ender").style.display="block";
        }
        else{
            document.getElementById("ender").style.display="none";
        }
    }
}