class map{
    constructor(map){
        this.name=map.name
        this.src=map;
        this.entityGroup=[];
        this.src.entity.forEach(e=>{
            this.entityGroup.push(e);
        });
    }
}

var ateliter={
    "name":"ateliter",
    "background":"ateliter.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,0,80,720]
        },
        {
            "type":"hitbox",
            "hitbox":[1200,0,80,720]
        },
        {
            "type":"door",
            "destinationMap":"A",
            "destinationX":320,
            "destinationY":0,
            "hitbox":[1040,320,240,320]
        },
        {
            "type":"text",
            "hitbox":[200,540,200,100],
            "text":[
                "测试1",
                "测试2"
            ],
            "once":true
        },
        {
            "type":"pot",
            "hitbox":[600,540,80,100]
        }
    ]
}
var A={
    "name":"A",
    "background":"",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,0,80,720]
        },
        {
            "type":"hitbox",
            "hitbox":[1200,0,80,720]
        },
        {
            "type":"door",
            "destinationMap":"ateliter",
            "destinationX":320,
            "destinationY":0,
            "hitbox":[1040,320,240,320]
        },
        {
            "type":"item",
            "itemname":"饮用水",
            "img":"item_img_1.png",
            "amount":3,
            "quality":[5,20,10],
            "trait":["难喝","好喝",""],
            "hitbox":[500,200,200,200]
        }
    ]
}