class map{
    constructor(map){
        this.name=map.name
        this.src=map;
        this.entityGroup=[];
        this.src.entity.forEach(e=>{
            this.entityGroup.push(e);
        });
        this.randomTrait();
    }
    randomTrait(){
        this.entityGroup.forEach(e=>{
            if(e.type=="item"){
                let trait=[];
                for(let i=0;i<e.amount;i++){
                    trait.push(mapTraitGroup[this.name][Math.floor(Math.random()*mapTraitGroup[this.name].length)]);
                }
                e.trait=trait;
            }
        });
    }
}

var mapTraitGroup={
    "pathNearAtelier":[
        "",
        "",
        "",
        "",
        "",
        "品质提升"
    ]
}

var atelier={
    "name":"atelier",
    "name1":"炼金工房",
    "background":"atelier.png",
    "entity":[
        {
            "type":"hitbox",//地板
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",//左侧墙
            "hitbox":[0,0,80,720]
        },
        {
            "type":"hitbox",//右侧墙
            "hitbox":[1200,0,80,370]
        },
        {
            "type":"hitbox",//门右边的碰撞箱
            "hitbox":[1280,240,80,480]
        },
        {
            "type":"door",
            "destinationMap":"pathNearAtelier",
            "destinationX":80,
            "destinationY":320,
            "hitbox":[1200,240,80,480]
        },
        {
            "type":"text",
            "hitbox":[200,540,200,100],
            "text":[
                "喵喵喵喵喵喵喵喵喵喵喵喵喵喵喵",
                "测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试"
            ],
            "once":true
        },
        {
            "type":"pot",
            "hitbox":[240,320,254,320]
        }
    ]
}
var pathNearAtelier={
    "name":"pathNearAtelier",
    "name1":"工房旁小路",
    "background":"pathNearAtelier.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,0,80,720]
        },
        {
            "type":"hitbox",
            "hitbox":[1200,0,80,720]
        },
        {
            "type":"door",
            "destinationMap":"atelier",
            "destinationX":1168,
            "destinationY":486,
            "hitbox":[1040,320,240,320]
        },
        {
            "type":"item",
            "itemname":"饮用水",
            "amount":3,
            "quality":[5,20,10],
            "trait":[],
            "hitbox":[500,400,50,50]
        },
        {
            "type":"recipeItem",
            "name":"喵",
            "hitbox":[600,400,200,200],
            "recipe":[
                {
                    "name":"丝薇丽银",
                    "time":8,
                    "recipe":{
                        "金属块":1,
                        "中和剂（红）":2,
                        "（石材）":2
                    }
                },
                {
                    "name":"黄金艾森矿",
                    "time":16,
                    "recipe":{
                        "丝薇丽银":1,
                        "中和剂（黄）":2,
                        "黄金色之岩":4
                    }
                },
                {
                    "name":"精灵银块",
                    "time":32,
                    "recipe":{
                        "黄金艾森矿":1,
                        "七色棱镜":1,
                        "残破矿石":3
                    }
                },
                {
                    "name":"海银",
                    "time":64,
                    "recipe":{
                        "精灵银块":1,
                        "黑洞":1,
                        "（神秘之力）":3
                    }
                }
            ]
        }
    ]
}