class map{
    constructor(map){
        this.name=map.name
        this.src=map;
        this.entityGroup=[];
        this.src.entity.forEach(e=>{
            this.entityGroup.push(e);
        });
        this.randomTrait();
        this.randonmQuality();
    }
    randomTrait(){
        this.entityGroup.forEach(e=>{
            if(e.type=="item"||e.type=="needToolItem"){
                let trait=[];
                for(let i=0;i<e.amount;i++){
                    trait.push(mapTraitGroup[this.name][Math.floor(Math.random()*mapTraitGroup[this.name].length)]);
                }
                e.trait=trait;
            }
        });
    }
    randonmQuality(){
        this.entityGroup.forEach(e=>{
            if(e.type=="item"||e.type=="needToolItem"){
                let quality=[];
                for(let i=0;i<e.amount;i++){
                    quality.push(mapQualityGroup[this.name][Math.floor(Math.random()*mapQualityGroup[this.name].length)]);
                }
                e.quality=quality;
            }
        });
    }
}
var Trial=[
    {
        "map":"CrystalCaveLeft",
        "name":"1",
        "hitbox":[1013,247,134,133],
        "item":[
            {
                "name":"野兽毛皮",
                "amount":4,
                "quality":[50,50,50,50],
                "trait":["品质提升","品质提升","品质提升","品质提升"]
            }
        ],
        "refreshTime":504
    },
    {
        "map":"dragonLeft",
        "name":"2",
        "hitbox":[906,450,182,182],
        "item":[
            {
                "name":"龙眼",
                "amount":1,
                "quality":[80],
                "trait":["究极之力"]
            },
            {
                "name":"龙之血晶",
                "amount":1,
                "quality":[80],
                "trait":["究极之力"]
            },
        ],
        "refreshTime":504
    },
]
var buystore=[
    {
        "map":"town",
        "name":"1",
        "hitbox":[452,340,375,300],
        "goods":[
            {
                "name":"冶炼秘术",
                "img":"stained-grimoire.webp",
                "amount":1,
                "quality":[100],
                "trait":[""],
                "price":250,
                "refreshTime":-1
            },
            {
                "name":"高等冶炼术",
                "img":"stained-grimoire.webp",
                "amount":1,
                "quality":[100],
                "trait":[""],
                "price":2500,
                "refreshTime":-1
            },
            {
                "name":"炸弹的制作方法",
                "img":"stained-grimoire.webp",
                "amount":1,
                "quality":[100],
                "trait":[""],
                "price":1000,
                "refreshTime":-1
            },
        ],
    },
    {
        "map":"town",
        "name":"2",
        "hitbox":[231,348,151,293],
        "goods":[
            {
                "name":"宝石雕刻术",
                "img":"stained-grimoire.webp",
                "amount":1,
                "quality":[100],
                "trait":[""],
                "price":3000,
                "refreshTime":-1
            },
            {
                "name":"鞣皮液",
                "img":"tanning-fluid.webp",
                "amount":2,
                "quality":[20,30],
                "trait":["品质提升","高价"],
                "price":30,
                "refreshTime":72
            },
            {
                "name":"星幻钥匙",
                "img":"key-to-the-stars.webp",
                "amount":2,
                "quality":[100,100],
                "trait":["品质提升+","品质提升+"],
                "price":1000,
                "refreshTime":-1
            },
            {
                "name":"微风香精油",
                "img":"breezy-aroma.webp",
                "amount":3,
                "quality":[50,50,50],
                "trait":["品质提升+","品质提升+","品质提升+"],
                "price":100,
                "refreshTime":72
            },
            {
                "name":"棉花",
                "img":"cotton-wool.webp",
                "amount":5,
                "quality":[25,25,30,30,40],
                "trait":["","品质提升","高价","","品质提升"],
                "price":15,
                "refreshTime":48
            },
        ],
    }
]

var mapTraitGroup = {
    "pathNearAtelier": [
        "", "", "", "", "",
        "品质提升", "低价", "高价"
    ],
    "pathToTheTown": [
        "", "", "", "", "",
        "品质提升", "品质提升", "品质提升",
        "品质提升+", "低价", "低价", "低价+",
        "高价", "高价"
    ],
    "CrystalCave": [
        "", "", "", "",        
        "品质提升", "品质提升", "品质提升",
        "品质提升+", "品质提升+", "品质提升++",
    ],
    "CrystalCaveRight": [
        "低价", "高价", "高价+", "高价+",        
        "品质提升", "品质提升", "品质提升",
        "品质提升+", "品质提升+", "品质提升++",
    ],
    "dragonHole": [
        "品质提升++", "超级品质", "究极之力"
    ],
    "mountainCave1": [
        "", "", "", "", "",
        "品质提升", "低价", "高价"
    ],
    "mountainCave2": [
        "品质提升", "品质提升+", "高价", "高价+"
    ],
    "mountainCave3": [
        "品质提升+", "品质提升++", "高价+", "高价++"
    ],
    "coldCave": [
        "品质提升", "品质提升+", "低价", "高价"
    ],
    "coldPlain": [
        "品质提升", "品质提升+", "低价", "高价"
    ],
    "coldPlainRight": [
        "品质提升+", "品质提升++", "高价", "高价+"
    ],
    "coldPalace": [
        "品质提升++", "超级品质", "高价++", "限定价格"
    ],
    "coldPlainDown": [
        "品质提升+", "品质提升++", "高价+", "高价++"
    ],
    "volcano": [
        "品质提升++", "超级品质", "究极之力"
    ],
    "forest": [
        "", "", "品质提升", "低价", "高价"
    ],
    "deepForest": [
        "品质提升", "品质提升+", "低价", "高价", "高价+"
    ],
    "deepestForest": [
        "品质提升+", "品质提升++", "高价", "高价+", "高价++"
    ],
    "thunderIsland": [
        "品质提升+", "品质提升++", "高价+", "高价++", "究极之力"
    ],
    "thunderRuins": [
        "品质提升++", "超级品质", "究极之力", "限定价格"
    ],
    "peak": [
        "品质提升++", "超级品质", "究极之力", "限定价格"
    ],
    "town": [
        "", "", "", "", ""
    ],
    "townRight": [
        "", "", "", "", ""
    ]
}
var mapQualityGroup = {
    "pathNearAtelier": [
        5, 5, 10, 10, 10, 10, 20
    ],
    "pathToTheTown": [
        10, 10, 10, 15, 15, 20, 25
    ],
    "CrystalCave": [
        10, 20, 20, 20, 20, 25, 25, 30, 30, 35, 35
    ],
    "CrystalCaveRight": [
        30, 30, 40, 40, 50, 50, 50
    ],
    "dragonHole": [
        80, 90, 100
    ],
    "mountainCave1": [
        15, 20, 25, 30
    ],
    "mountainCave2": [
        25, 30, 35, 40
    ],
    "mountainCave3": [
        35, 40, 45, 50
    ],
    "coldCave": [
        20, 25, 30, 35
    ],
    "coldPlain": [
        25, 30, 35, 40
    ],
    "coldPlainRight": [
        30, 35, 40, 45
    ],
    "coldPalace": [
        40, 45, 50, 55
    ],
    "coldPlainDown": [
        35, 40, 45, 50
    ],
    "volcano": [
        50, 55, 60, 65
    ],
    "forest": [
        10, 15, 20, 25
    ],
    "deepForest": [
        20, 25, 30, 35
    ],
    "deepestForest": [
        30, 35, 40, 45
    ],
    "thunderIsland": [
        40, 45, 50, 55
    ],
    "thunderRuins": [
        50, 55, 60, 65
    ],
    "peak": [
        60, 65, 70, 75
    ],
    "town": [
        0, 0, 0, 0, 0
    ],
    "townRight": [
        0, 0, 0, 0, 0
    ]
}

var atelier={
    "name":"atelier",
    "name1":"炼金工房",
    "background":"atelier.png",
    "bgm":"阿知波大輔 - 春風のポーレチカ.mp3",
    "entity":[
        {
            "type":"hitbox",//地板
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",//左侧墙
            "hitbox":[0,-240,80,960]
        },
        {
            "type":"hitbox",//右侧墙
            "hitbox":[1200,-240,80,610]
        },
        {
            "type":"hitbox",//门右边的碰撞箱
            "hitbox":[1280,240,80,480]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"door",
            "destinationMap":"pathNearAtelier",
            "destinationX":0,
            "destinationY":438,
            "hitbox":[1200,240,80,480]
        },
        {
            "type":"text",
            "hitbox":[200,540,200,100],
            "text":[
                "按E快进文本，文本结束后按E继续，按ctrl跳过文本",
                "默认按键:tab暂停游戏，ad左右移动，空格跳跃，按q攻击，制作旅人之鞋后按shift疾跑，制作飞翔之衣后按w+空格高跳",
                "在光点处按E采集，在门处按E前往其他地图，屏幕左边出现E提示时按E可以进行交互",
                "与炼金釜交互以进行调和，炼金釜界面中显示你获得的配方，材料不足无法制作。",
                "注意：如果配方中两个所需材料包含同一种物品，那么如果你在上一步投料时把下一步的所需材料投入，使下一步所需材料不足，那么将无法制作。请尤其注意这一点",
                "部分配方在地图中采集获得，部分配方在城镇中购买，部分配方通过调和前置配方解锁",
                "你需要在120天内调和天启与智慧之杖以进入非坏结局的结局，否则进入坏结局",
                "结局将由你制作的天启与智慧之杖的品质决定，最好结局要求你制作出炼金术士们所追求之物"
            ],
            "once":true
        },
        {
            "type":"pot",
            "hitbox":[240,320,254,320]
        }
    ]
}
var pathNearAtelier={
    "name":"pathNearAtelier",
    "name1":"工房旁小路",
    "background":"pathNearAtelier.png",
    "bgm":"阿知波大輔 - 春風のポーレチカ.mp3",
    "entity":[
        {
            "type":"hitbox",//地板
            "hitbox":[0,640,1360,80]
        },
        {
            "type":"hitbox",//左侧墙
            "hitbox":[0,0,80,393]
        },
        {
            "type":"hitbox",//上台阶
            "hitbox":[0,560,320,40]
        },
        {
            "type":"hitbox",//下台阶
            "hitbox":[0,600,360,400]
        },
        {
            "type":"hitbox",//右侧碰撞箱
            "hitbox":[1360,0,80,720]
        },
        {
            "type":"hitbox",//左门左边的碰撞箱
            "hitbox":[-80,393,80,167]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"text",
            "hitbox":[0,393,80,167],
            "text":[
                "每进入新的场景，都会消耗4小时的时间。（从炼金工房出去除外）"
            ],
            "once":true
        },
        {
            "type":"door",
            "destinationMap":"atelier",
            "destinationX":1168,
            "destinationY":518,
            "hitbox":[0,393,80,167]
        },
        {
            "type":"entrance",
            "destinationMap":"pathToTheTown",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"item",
            "itemname":"饮用水",
            "amount":6,
            "quality":[],
            "trait":[],
            "hitbox":[732,504,128,128]
        },
        {
            "type":"item",
            "itemname":"寻常草",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[465,550,90,90]
        },
    ]
}
var pathToTheTown={
    "name":"pathToTheTown",
    "name1":"通往城镇的小路",
    "background":"pathToTheTown.png",
    "bgm":"矢野達也 - やってみよう!.mp3",
    "entity":[
        {
            "type":"hitbox",//地板左
            "hitbox":[-80,640,600,160]
        },
        {
            "type":"hitbox",//地板右
            "hitbox":[680,640,680,160]
        },
        {
            "type":"hitbox",//左侧碰撞箱
            "hitbox":[-160,0,80,720]
        },
        {
            "type":"hitbox",//右侧碰撞箱
            "hitbox":[1420,0,80,720]
        },
        {
            "type":"hitbox",//下侧碰撞箱
            "hitbox":[520,800,160,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"item",
            "itemname":"直木",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[160,512,128,128]
        },
        {
            "type":"entrance",
            "destinationMap":"pathNearAtelier",
            "destinationX":1168,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCave",
            "destinationX":250,
            "destinationY":0,
            "hitbox":[520,720,160,80]
        },
        {
            "type":"entrance",
            "destinationMap":"forest",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"item",
            "itemname":"蓝色的花",
            "amount":2,
            "quality":[],
            "trait":[],
            "hitbox":[732,585,81,81]
        },
        {
            "type":"item",
            "itemname":"黄色的花",
            "amount":2,
            "quality":[],
            "trait":[],
            "hitbox":[838,594,66,66]
        },
        {
            "type":"item",
            "itemname":"红色的花",
            "amount":2,
            "quality":[],
            "trait":[],
            "hitbox":[920,594,66,66]
        },
        {
            "type":"item",
            "itemname":"绿色的花",
            "amount":2,
            "quality":[],
            "trait":[],
            "hitbox":[1014,588,85,85]
        },
        {
            "type":"item",
            "itemname":"白色的花",
            "amount":2,
            "quality":[],
            "trait":[],
            "hitbox":[1146,585,85,85]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "温柔可亲的森林。阳光穿透层叠的巨树枝桠，在苔藓覆盖的地面洒下破碎的光斑；空气里飘着铃兰与某种菌菇混合的甜香。"
            ],
            "once":true
        },
    ]
}
var CrystalCave={
    "name":"CrystalCave",
    "name1":"水晶洞穴",
    "background":"CrystalCave.jpg",
    "bgm":"矢野達也 - 古の風の跡.mp3",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,0,250,80]
        },
        {
            "type":"hitbox",
            "hitbox":[640,0,250,80]
        },
        {
            "type":"hitbox",
            "hitbox":[960,0,320,96]
        },
        {
            "type":"hitbox",
            "hitbox":[260,150,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[430,350,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[100,450,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[1160,354,120,10]
        },
        {
            "type":"hitbox",
            "hitbox":[1000,440,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-240,1280,80]
        },
        {
            "type":"puni",
            "name":"蓝噗尼",
            "img":"blue-puni",
            "hitbox":[180,366,64,84],
            "actRange":[110,366,140,84],
            "damage":1,
            "hearts":8
        },
        {
            "type":"entrance",
            "destinationMap":"pathToTheTown",
            "destinationX":560,
            "destinationY":398,
            "hitbox":[250,-80,490,80]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCaveRight",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,450,80,190]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCaveRight",
            "destinationX":0,
            "destinationY":318,
            "hitbox":[1280,95,80,260]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCaveLeft",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"item",
            "itemname":"艾森矿",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[1076,354,81,81]
        },
        {
            "type":"item",
            "itemname":"艾森矿",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[105,555,81,81]
        },
        {
            "type":"item",
            "itemname":"白砂",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[130,365,81,81]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "火把的光芒在潮湿的岩壁上投下晃动的影子，空气中满是铁屑与潮湿泥土的味道。来这里寻找矿石一定是个好选择。"
            ],
            "once":true
        },
    ]
}
var CrystalCaveRight={
    "name":"CrystalCaveRight",
    "name1":"水晶洞穴右",
    "background":"CrystalCaveRight.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,440,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[350,350,320,10]
        },
        {
            "type":"hitbox",
            "hitbox":[670,340,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[830,400,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[1120,450,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,450]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCave",
            "destinationX":1196,
            "destinationY":232,
            "hitbox":[-80,0,80,440]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCave",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,450,80,270]
        },
        {
            "type":"entrance",
            "destinationMap":"coldCave",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,450,80,270]
        },
        {
            "type":"needToolItem",
            "itemname":"黄金色之岩",
            "amount":1,
            "quality":[],
            "trait":[],
            "needTool":"十字镐",
            "hitbox":[682,496,103,103]
        },
        {
            "type":"item",
            "itemname":"石灰岩",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[897,0,125,125]
        },
        {
            "type":"item",
            "itemname":"可燃灰砂",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[469,0,112,112]
        },
        {
            "type":"item",
            "itemname":"啪汽啪汽水",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[992,509,125,125]
        },
    ]
}
var CrystalCaveLeft={
    "name":"CrystalCaveLeft",
    "name1":"水晶洞穴左",
    "background":"CrystalCaveLeft.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[370,260,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[550,430,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[1000,380,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCave",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"door",
            "destinationMap":"dragonHole",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[552,272,158,158]
        },
    ]
}
var coldCave={
    "name":"coldCave",
    "name1":"冷洞",
    "background":"coldCave.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,230,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[370,380,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[800,490,320,10]
        },
        {
            "type":"hitbox",
            "hitbox":[370,540,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,0,80,240]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCaveRight",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,240,80,480]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlain",
            "destinationX":0,
            "destinationY":228,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"recipeItem",
            "name":"鞋匠手册",
            "hitbox":[6,81,145,145],
            "recipe":[
                {
                    "name":"旅人之鞋",
                    "time":24,
                    "recipe":{
                        "鞣制皮革":2,
                        "（布料）":2,
                        "（线材）":1
                    }
                },
            ]
        },
        {
            "type":"item",
            "itemname":"不冻妙水",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[961,343,139,139]
        },
        {
            "type":"needToolItem",
            "itemname":"银粉矿石",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"十字镐",
            "hitbox":[164,437,132,132]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "洞口覆盖着厚厚的冰层，寒气透过你的靴子。洞穴地面的冰面光滑如镜，倒映着洞顶悬挂的冰柱。"
            ],
            "once":true
        },
    ]
}
var coldPlain={
    "name":"coldPlain",
    "name1":"寒冷平原",
    "background":"coldPlain.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,350,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[160,480,320,16]
        },
        {
            "type":"hitbox",
            "hitbox":[810,400,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[1120,300,160,340]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,360,80,370]
        },
        {
            "type":"entrance",
            "destinationMap":"coldCave",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,350]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlainRight",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"item",
            "itemname":"白雪菇",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[850,529,107,107]
        },
    ]
}
var coldPlainRight={
    "name":"coldPlianRight",
    "name1":"寒冷平原右",
    "background":"coldPlainRight.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[290,260,320,10]
        },
        {
            "type":"hitbox",
            "hitbox":[890,380,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,650,80]
        },
        {
            "type":"hitbox",
            "hitbox":[880,640,400,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlain",
            "destinationX":1196,
            "destinationY":178,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlainDown",
            "destinationX":767,
            "destinationY":1,
            "hitbox":[650,720,230,80]
        },
        {
            "type":"door",
            "destinationMap":"coldPalace",
            "destinationX":0,
            "destinationY":178,
            "hitbox":[1078,399,202,240]
        },
    ]
}
var coldPalace={
    "name":"coldPalace",
    "name1":"冷宫",
    "background":"coldPalace.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[480,186,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[750,316,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[1050,450,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,300,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[300,450,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[460,530,320,10]
        },
        {
            "type":"hitbox",
            "hitbox":[870,640,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,310,80,570]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,880]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlainRight",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,300]
        },
        {
            "type":"dog",
            "name":"",
            "img":"dog",
            "hitbox":[0,800,1280,80],
            "damage":999,
            "hearts":2000
        },
        {
            "type":"item",
            "itemname":"闪亮原色砂",
            "amount":2,
            "quality":[],
            "trait":[],
            "hitbox":[319,323,120,120]
        },
        {
            "type":"item",
            "itemname":"闪亮原色砂",
            "amount":1,
            "quality":[],
            "trait":[],
            "hitbox":[509,75,101,101]
        },
        {
            "type":"recipeItem",
            "name":"洁白布料的编制方法",
            "hitbox":[544,368,151,151],
            "recipe":[
                {
                    "name":"天鹅绒布",
                    "time":4,
                    "recipe":{
                        "白雪菇":2,
                        "捆起来的金线":2,
                        "（万灵药）":1
                    }
                },
            ]
        }
    ]
}
var coldPlainDown={
    "name":"coldPlainDown",
    "name1":"寒冷平原下",
    "background":"coldPlainDown.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[650,220,320,10]
        },
        {
            "type":"hitbox",
            "hitbox":[400,360,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,640,80]
        },
        {
            "type":"hitbox",
            "hitbox":[160,480,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[1020,640,260,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,650,80]
        },
        {
            "type":"hitbox",
            "hitbox":[970,-80,310,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlainRight",
            "destinationX":727,
            "destinationY":423,
            "hitbox":[650,-80,320,80]
        },
        {
            "type":"entrance",
            "destinationMap":"volcano",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"dog",
            "name":"",
            "img":"dog",
            "hitbox":[0,800,1280,80],
            "damage":999,
            "hearts":2000
        },
        {
            "type":"item",
            "itemname":"炙热喷水",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[424,243,107,107]
        },
        {
            "type":"item",
            "itemname":"炙热喷水",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[430,521,107,107]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "灼热的气息从洞口喷涌而出，连空气都仿佛被烤得扭曲。洞内的地面布满裂缝，暗红色的岩浆在裂缝中缓缓流动：小心烫伤！"
            ],
            "once":true
        },
    ]
}
var volcano={
    "name":"volcano",
    "name1":"火山",
    "background":"volcano.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,340,320,10]
        },
        {
            "type":"hitbox",
            "hitbox":[525,241,480,10]
        },
        {
            "type":"hitbox",
            "hitbox":[430,460,160,10]
        },
        {
            "type":"hitbox",
            "hitbox":[640,640,640,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-160,-80,1440,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-160,0,80,800]
        },
        {
            "type":"entrance",
            "destinationMap":"coldPlainDown",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"dog",
            "name":"",
            "img":"dog",
            "hitbox":[-160,800,1440,80],
            "damage":999,
            "hearts":2000
        },
        {
            "type":"item",
            "itemname":"炙热喷水",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[461,360,87,87]
        },
        {
            "type":"recipeItem",
            "name":"如水一般的金属冶炼法",
            "hitbox":[75,165,165,165],
            "recipe":[
                {
                    "name":"易熔金属",
                    "time":4,
                    "recipe":{
                        "银粉矿石":1,
                        "炙热喷水":2,
                        "（矿石）":2
                    }
                }
            ]
        }
    ]
}
var dragonHole={
    "name":"dragonHole",
    "name1":"龙洞",
    "background":"dragonHole.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[350,300,160,50]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"dragon",
            "hitbox":[0,0,800,640]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"CrystalCaveLeft",
            "destinationX":587,
            "destinationY":306,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"dragonLeft",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"needToolItem",
            "itemname":"残破矿石",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"爆破用炎烧",
            "hitbox":[342,405,187,187],
            "use":1
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "你踏入洞穴的瞬间，温热的气流裹挟着古老的威压扑面而来。你似乎察觉到一些危险的气息……"
            ],
            "once":true
        },
    ]
}
var dragonLeft={
    "name":"dragonLeft",
    "name1":"龙洞左",
    "background":"dragonLeft.jpg",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[501,480,288,160]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"dragonHole",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"recipeItem",
            "name":"传说中的冶炼法",
            "hitbox":[507,156,272,272],
            "recipe":[
                {
                    "name":"海银",
                    "time":16,
                    "recipe":{
                        "精灵银块":1,
                        "黑洞":1,
                        "银粉矿石":2
                    }
                },
            ]
        }
    ]
}
var forest={
    "name":"forest",
    "name1":"森林",
    "background":"forest.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[228,475,214,23]
        },
        {
            "type":"hitbox",
            "hitbox":[587,338,212,22]
        },
        {
            "type":"hitbox",
            "hitbox":[987,178,214,23]
        },
        {
            "type":"hitbox",
            "hitbox":[177,151,214,24]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"pathToTheTown",
            "destinationX":1168,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"town",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"door",
            "destinationMap":"deepForest",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[511,421,218,218]
        },
        {
            "type":"item",
            "itemname":"红色的花",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[69,540,96,96]
        },
        {
            "type":"item",
            "itemname":"唐木叶",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[238,73,81,81]
        },
        {
            "type":"item",
            "itemname":"唐木叶",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[1049,94,83,83]
        },
    ]
}
var deepForest={
    "name":"deepForest",
    "name1":"森林深处",
    "background":"deepForest.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[735,521,195,19]
        },
        {
            "type":"hitbox",
            "hitbox":[371,366,190,18]
        },
        {
            "type":"hitbox",
            "hitbox":[69,229,194,21]
        },
        {
            "type":"hitbox",
            "hitbox":[650,177,190,18]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"forest",
            "destinationX":565,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"deepestForest",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"recipeItem",
            "name":"捕虫网制作方法",
            "hitbox":[133,505,121,121],
            "recipe":[
                {
                    "name":"捕虫网",
                    "time":4,
                    "recipe":{
                        "捆起来的金线":2,
                        "（木材）":2,
                        "（线材）":2
                    }
                },
            ]
        },
        {
            "type":"needToolItem",
            "itemname":"星之瓢虫",
            "amount":3,
            "quality":[],
            "trait":[],
            "needTool":"捕虫网",
            "hitbox":[543,507,104,104]
        },
        {
            "type":"needToolItem",
            "itemname":"毒杀蛙",
            "amount":4,
            "quality":[],
            "trait":[],
            "needTool":"捕虫网",
            "hitbox":[1081,483,104,104]
        },
        {
            "type":"item",
            "itemname":"唐木叶",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[684,54,110,10]
        },
        {
            "type":"item",
            "itemname":"黏银丝",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[348,242,128,128]
        },
    ]
}
var deepestForest={
    "name":"deepestForest",
    "name1":"森林最深处",
    "background":"deepestForest.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,399,80]
        },
        {
            "type":"hitbox",
            "hitbox":[732,640,546,80]
        },
        {
            "type":"hitbox",
            "hitbox":[430,473,268,19]
        },
        {
            "type":"hitbox",
            "hitbox":[781,324,268,19]
        },
        {
            "type":"hitbox",
            "hitbox":[53,329,268,19]
        },
        {
            "type":"hitbox",
            "hitbox":[414,149,268,19]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"deepForest",
            "destinationX":1168,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"deephole",
            "destinationX":950,
            "destinationY":0,
            "hitbox":[0,720,1280,80]
        },
        {
            "type":"recipeItem",
            "name":"炼金蜂蜜制作方法",
            "hitbox":[491,20,121,121],
            "recipe":[
                {
                    "name":"生命之蜜",
                    "time":4,
                    "recipe":{
                        "微风香精油":1,
                        "（虫）":3,
                        "（万灵药）":2,
                        "（中和剂）":1
                    }
                },
                {
                    "name":"翠岚之滴",
                    "time":4,
                    "recipe":{
                        "生命之蜜":1,
                        "睿智绿宝石":1,
                        "雷电蜻蜓":3,
                        "（万灵药）":2,
                        "（中和剂）":1
                    }
                },
            ]
        },
        {
            "type":"needToolItem",
            "itemname":"幼亚龙毛虫",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"捕虫网",
            "hitbox":[97,475,121,121]
        },
        {
            "type":"item",
            "itemname":"夕阳草",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[1085,475,121,121]
        },
        {
            "type":"item",
            "itemname":"夕阳草",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[492,415,92,92]
        },
        {
            "type":"item",
            "itemname":"黏银丝",
            "amount":3,
            "quality":[],
            "trait":[],
            "hitbox":[122,184,134,134]
        },
        {
            "type":"item",
            "itemname":"黏银丝",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[755,497,110,110]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "这里只有零星的光透过叶片缝隙投在覆盖着腐殖土的地面上，空气里充斥着潮湿的腐叶味与某种奇异花卉的腥甜。或许要谨慎一点。"
            ],
            "once":true
        },
    ]
}
var thunderIsland={
    "name":"thunderIsland",
    "name1":"轰雷岛",
    "bgm":"悠花ユカ - 星追いのルルア ～コーラス.mp3",
    "background":"thunderIsland.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,265,80]
        },
        {
            "type":"hitbox",
            "hitbox":[473,640,267,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1018,640,261,80]
        },
        {
            "type":"hitbox",
            "hitbox":[281,466,179,16]
        },
        {
            "type":"hitbox",
            "hitbox":[795,362,179,17]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"townRight",
            "destinationX":110,
            "destinationY":0,
            "hitbox":[265,720,208,80]
        },
        {
            "type":"entrance",
            "destinationMap":"townRight",
            "destinationX":738,
            "destinationY":0,
            "hitbox":[738,720,280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"thunderRuins",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"needToolItem",
            "itemname":"雷电蜻蜓",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"捕虫网",
            "hitbox":[535,516,118,118]
        },
        {
            "type":"needToolItem",
            "itemname":"雷电矿",
            "amount":1,
            "quality":[],
            "trait":[],
            "needTool":"爆破用炎烧",
            "hitbox":[278,70,160,160]
        },
    ]
}
var thunderRuins={
    "name":"thunderRuins",
    "name1":"轰雷废墟",
    "background":"thunderRuins.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,276,80]
        },
        {
            "type":"hitbox",
            "hitbox":[597,640,681,80]
        },
        {
            "type":"hitbox",
            "hitbox":[301,485,286,30]
        },
        {
            "type":"hitbox",
            "hitbox":[702,176,286,35]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"thunderIsland",
            "destinationX":1168,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"deephole",
            "destinationX":640,
            "destinationY":0,
            "hitbox":[0,720,1280,80]
        },
        {
            "type":"needToolItem",
            "itemname":"雷电矿",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"爆破用炎烧",
            "hitbox":[717,483,148,148]
        },
    ]
}
var town={
    "name":"town",
    "name1":"城镇",
    "background":"town.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-240,1280,80]
        },
        {
            "type":"sellstore",
            "name":"1",
            "hitbox":[996,348,151,293]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"forest",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"townRight",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "橡木制成的拱门下挂着褪色的纹章旗，铁匠铺的打铁声与酒馆的欢笑声在石板路上交织——热闹非凡的集市！或许可以尝试在这里购买到你想要的东西。",
                "左面两家为商店，你可以把物品卖给右边的人"
            ],
            "once":true
        },
    ]
}
var townRight={
    "name":"townRight",
    "name1":"城镇右",
    "background":"townRight.jpg",
    "bgm":"矢野達也 - やってみよう!.mp3",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[90,270,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[270,420,320,16]
        },
        {
            "type":"hitbox",
            "hitbox":[960,400,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[1120,380,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,960,80]
        },
        {
            "type":"hitbox",
            "hitbox":[960,700,320,20]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-160,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"town",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"mountainCave1",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,396,80,340]
        },
        {
            "type":"entrance",
            "destinationMap":"peak",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,380]
        },
        {
            "type":"entrance",
            "destinationMap":"thunderIsland",
            "destinationX":150,
            "destinationY":518,
            "hitbox":[0,-80,400,80]
        },
        {
            "type":"dog",
            "name":"狗",
            "img":"dog",
            "hitbox":[754,550,90,90],
            "damage":2,
            "hearts":20
        },
    ]
}
var peak={
    "name":"peak",
    "name1":"山顶",
    "background":"peak.jpg",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[60,180,480,16]
        },
        {
            "type":"hitbox",
            "hitbox":[800,230,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[240,370,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[400,400,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[800,455,160,16]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"townRight",
            "destinationX":1196,
            "destinationY":258,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"chest",
            "name":"炼金术的奥义",
            "hitbox":[825,102,128,128],
            "recipe":[
                {
                    "name":"万能中和剂（虹）",
                    "time":64,
                    "recipe":{
                        "纯水":2,
                        "龙之血晶":1,
                        "中和剂（白）":1,
                        "（中和剂）":3
                    }
                },
                {
                    "name":"炼金黏土",
                    "time":4,
                    "recipe":{
                        "（石材）":2,
                        "（水）":1,
                        "（中和剂）":1
                    }
                },
                {
                    "name":"黑洞",
                    "time":128,
                    "recipe":{
                        "星幻钥匙":1,
                        "万能中和剂（虹）":1,
                        "（宝石）":2
                    }
                },
                {
                    "name":"朔月暗雾",
                    "time":4,
                    "recipe":{
                        "中和剂（白）":1,
                        "幼亚龙毛虫":2,
                        "（有毒材料）":2,
                        "夕阳草":3
                    }
                },
            ]
        },
        {
            "type":"needToolItem",
            "itemname":"星之粉",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"爆破用炎烧",
            "use":1,
            "hitbox":[240,52,111,111]
        },
        {
            "type":"item",
            "itemname":"黄色的花",
            "amount":4,
            "quality":[],
            "trait":[],
            "hitbox":[70,459,139,139]
        },
        {
            "type":"item",
            "itemname":"石灰岩",
            "amount":5,
            "quality":[],
            "trait":[],
            "hitbox":[553,503,125,125]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "大风呼啸着掠过山顶，卷起碎石与枯草，远处的云海在脚下翻涌，仿佛伸手就能触摸到天空。"
            ],
            "once":true
        },
    ]
}
var mountainCave1={
    "name":"mountainCave1",
    "name1":"山洞",
    "background":"mountainCave1.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[0,272,176,58]
        },
        {
            "type":"hitbox",
            "hitbox":[431,154,187,29]
        },
        {
            "type":"hitbox",
            "hitbox":[633,325,318,25]
        },
        {
            "type":"hitbox",
            "hitbox":[482,474,186,27]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-240,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[-80,-240,80,520]
        },
        {
            "type":"entrance",
            "destinationMap":"townRight",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,310,80,410]
        },
        {
            "type":"entrance",
            "destinationMap":"mountainCave2",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,-240,80,960]
        },
        {
            "type":"needToolItem",
            "itemname":"蓝宝石原石",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"十字镐",
            "hitbox":[818,185,138,138]
        },
        {
            "type":"recipeItem",
            "name":"皮革鞣制技巧",
            "hitbox":[0,149,121,121],
            "recipe":[
                {
                    "name":"鞣制皮革",
                    "time":16,
                    "recipe":{
                        "野兽毛皮":2,
                        "鞣皮液":2,
                        "（水）":2
                    }
                }
            ]
        },
        {
            "type":"text",
            "hitbox":[0,0,1280,720],
            "text":[
                "洞口被藤蔓与灌木遮掩，进入后你会看见岩壁上天然形成的石柱。"
            ],
            "once":true
        },
    ]
}
var mountainCave2={
    "name":"mountainCave2",
    "name1":"山洞",
    "background":"mountainCave2.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[159,317,287,22]
        },
        {
            "type":"hitbox",
            "hitbox":[650,194,259,26]
        },
        {
            "type":"hitbox",
            "hitbox":[1069,320,187,21]
        },
        {
            "type":"hitbox",
            "hitbox":[919,494,253,23]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[0,0,355,50]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"mountainCave1",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"entrance",
            "destinationMap":"mountainCave3",
            "destinationX":0,
            "destinationY":518,
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"needToolItem",
            "itemname":"黄宝石原石",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"十字镐",
            "hitbox":[682,496,103,103]
        },
        {
            "type":"needToolItem",
            "itemname":"红宝石原石",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"十字镐",
            "hitbox":[247,501,139,139]
        },
        {
            "type":"recipeItem",
            "name":"基础宝石雕刻手册",
            "hitbox":[222,155,163,163],
            "recipe":[
                {
                    "name":"热情红宝石",
                    "time":4,
                    "recipe":{
                        "红宝石原石":4,
                        "抛光液":4,
                        "（燃料）":2
                    }
                },
                {
                    "name":"高贵蓝宝石",
                    "time":6,
                    "recipe":{
                        "热情红宝石":1,
                        "蓝宝石原石":4,
                        "纯水":4
                    }
                },
                {
                    "name":"诚实黄宝石",
                    "time":8,
                    "recipe":{
                        "高贵蓝宝石":1,
                        "黄宝石原石":4,
                        "（金属）":3
                    }
                },
                {
                    "name":"睿智绿宝石",
                    "time":16,
                    "recipe":{
                        "诚实黄宝石":1,
                        "绿宝石原石":4,
                        "（气体）":3
                    }
                }
            ]
        }
    ]
}
var mountainCave3={
    "name":"mountainCave3",
    "name1":"山洞",
    "background":"mountainCave3.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[885,0,393,78]
        },
        {
            "type":"hitbox",
            "hitbox":[598,170,257,13]
        },
        {
            "type":"hitbox",
            "hitbox":[274,319,315,27]
        },
        {
            "type":"hitbox",
            "hitbox":[771,422,344,22]
        },
        {
            "type":"hitbox",
            "hitbox":[0,640,1280,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1280,0,80,720]
        },
        {
            "type":"hitbox",
            "hitbox":[0,-80,1280,80]
        },
        {
            "type":"entrance",
            "destinationMap":"mountainCave2",
            "destinationX":1196,
            "destinationY":518,
            "hitbox":[-80,0,80,720]
        },
        {
            "type":"needToolItem",
            "itemname":"绿宝石原石",
            "amount":2,
            "quality":[],
            "trait":[],
            "needTool":"十字镐",
            "hitbox":[912,235,181,181]
        },
        {
            "type":"needToolItem",
            "itemname":"钻石原石",
            "amount":1,
            "quality":[],
            "trait":[],
            "needTool":"爆破用炎烧",
            "hitbox":[1125,521,117,117],
            "use":1
        },
    ]
}
var deephole={
    "name":"deephole",
    "name1":"",
    "background":"deephole.png",
    "entity":[
        {
            "type":"hitbox",
            "hitbox":[-240,0,880,80]
        },
        {
            "type":"hitbox",
            "hitbox":[1440,0,880,80]
        },
        {
            "type":"dog",
            "name":"",
            "img":"dog",
            "hitbox":[-160,800,1600,80],
            "damage":999,
            "hearts":2000
        },
        {
            "type":"recipeItem",
            "name":"",
            "hitbox":[1280,600,200,200],
            "recipe":[
                {
                    "name":"贤者之石",
                    "time":4,
                    "recipe":{
                        "海银":2,
                        "万能中和剂（虹）":2,
                        "大地之母":1,
                        "百万水晶":1
                    }
                },
            ]
        },
    ]
}