class recipeGroup{
    constructor(){
        this.init()
    }
    init(){
        this.recipe=[
            {
                "name":"天启与智慧之杖",
                "time":256,
                "recipe":{
                    "海银":1,
                    "百万水晶":1,
                    "（万灵药）":2
                }
            },
            {
                "name":"中和剂（红）",
                "time":3,
                "recipe":{
                    "红色的花":1,
                    "（水）":1,
                    "（火药）":2
                }
            },
            {
                "name":"中和剂（蓝）",
                "time":3,
                "recipe":{
                    "蓝色的花":1,
                    "（水）":3,
                }
            },
            {
                "name":"中和剂（黄）",
                "time":3,
                "recipe":{
                    "黄色的花":1,
                    "（水）":1,
                    "（砂）":2
                }
            },
            {
                "name":"中和剂（绿）",
                "time":3,
                "recipe":{
                    "绿色的花":1,
                    "（水）":1,
                    "（植物）":2
                }
            },
            {
                "name":"金属块",
                "time":4,
                "recipe":{
                    "艾森矿":2,
                    "（砂）":1,
                    "（燃料）":1
                }
            }
        ]
    }
}