class saveMap{
    constructor(){
        this.atelier=atelier;
        this.pathNearAtelier=pathNearAtelier;
    }
}
class saveManager{
    constructor(game){
        this.username=localStorage.getItem("LA-username");
        this.init(game)
    }
    init(game){
        if(!localStorage.getItem("LA-save-"+this.username)){
            game.changeMap(atelier);
            this.save(game);
        }
    }
    save(game){
        this.storage=game.storage.item;
        this.bag=game.bag.item;
        this.pos=[game.Lilies.x,game.Lilies.y];
        this.RecipeGroup=game.RecipeGroup;
        this.position=game.Map.name;
        this.map=new saveMap;
        this.timer=game.timer;
        this.ender=game.EndChecker.ender;
        this.achievement=game.achievement.achievements;
        localStorage.setItem("LA-save-"+this.username,true);
        localStorage.setItem("LA-save-"+this.username+"storage",JSON.stringify(this.storage));
        localStorage.setItem("LA-save-"+this.username+"bag",JSON.stringify(this.bag));
        localStorage.setItem("LA-save-"+this.username+"pos",JSON.stringify(this.pos));
        localStorage.setItem("LA-save-"+this.username+"RecipeGroup",JSON.stringify(this.RecipeGroup));
        localStorage.setItem("LA-save-"+this.username+"position",JSON.stringify(this.position));
        localStorage.setItem("LA-save-"+this.username+"map",JSON.stringify(this.map));
        localStorage.setItem("LA-save-"+this.username+"timer",JSON.stringify(this.timer));
        localStorage.setItem("LA-save-"+this.username+"ender",JSON.stringify(this.ender));
        localStorage.setItem("LA-save-"+this.username+"achievement",JSON.stringify(this.achievement));
    }
    load(game){
        this.storage=JSON.parse(localStorage.getItem("LA-save-"+this.username+"storage"));
        this.bag=JSON.parse(localStorage.getItem("LA-save-"+this.username+"bag"));
        this.pos=JSON.parse(localStorage.getItem("LA-save-"+this.username+"pos"));
        this.RecipeGroup=JSON.parse(localStorage.getItem("LA-save-"+this.username+"RecipeGroup"));
        this.position=JSON.parse(localStorage.getItem("LA-save-"+this.username+"position"));
        this.map=JSON.parse(localStorage.getItem("LA-save-"+this.username+"map"));
        this.timer=JSON.parse(localStorage.getItem("LA-save-"+this.username+"timer"));
        this.ender=JSON.parse(localStorage.getItem("LA-save-"+this.username+"ender"));
        this.achievement=JSON.parse(localStorage.getItem("LA-save-"+this.username+"achievement"));
        game.storage.item=this.storage;
        game.bag.item=this.bag;
        game.Lilies.x=this.pos[0];
        game.Lilies.y=this.pos[1];
        game.RecipeGroup=this.RecipeGroup;
        for(let key in this.map){
            globalThis[this.map[key].name]=this.map[key];
        }
        game.timer=this.timer;
        game.EndChecker.ender=this.ender;
        game.achievement.achievements=this.achievement;
        game.changeMap(eval(this.position));
    }
}