class talk{
    constructor(){
        this.talkBox=document.getElementsByClassName("talkContainer")[0];
        this.index=0;
        this.displayed=false;
        this.timeout=null;
    }
    display(text,speed){
        this.talkBox.style.display="block";
        if(this.index<text.length){
            this.talkBox.innerHTML+=text.charAt(this.index);
            this.index++;
            this.timeout=setTimeout(()=>{
                this.display(text,speed);
            },Math.floor(1000/speed));
        }
        else{
            this.displayed=true;
        }
    }
    clear(){
        this.index=0;
        this.displayed=false;
        this.talkBox.innerHTML="";
    }
    hide(){
        this.talkBox.style.display="none";
    }
}