class talk{
    constructor(){
        this.talkBox=document.getElementsByClassName("talkContainer")[0];
        this.index=0;
        this.displayed=false;
        this.timeout=null;
    }
    display(text,speed,talk){
        talk.talkBox.style.display="block";
        if(talk.index<text.length){
            talk.talkBox.innerHTML=text.charAt(this.index);
            talk.index++;
            talk.timeout=setTimeout(()=>{
                talk.display(text,speed,talk);
            },Math.floor(1000/speed));
        }
        else{
            talk.displayed=true;
        }
    }
    see(text){
        this.talkBox.innerHTML+=text+"<br>";
        this.talkBox.style.display="block";
        this.displayed=true;
    }
    clear(){
        this.index=0;
        this.displayed=false;
        this.talkBox.innerHTML="";
    }
    hide(){
        this.talkBox.style.display="none";
    }
}